# Global information
source-id: "dydx-mainnet-1"
config-version: 1
properties:
  title: "dYdX"
  hex: "#12121d"
  logo: "ar://34RVRPI9Ume67ZdNhqwQ42GkZa0NoulBXNiJFJQZ6uc"
  description: "dYdX chain is an open-source application specific blockchain software that can power a decentralized perpetuals exchange. This standalone blockchain software is open-sourced by dYdX Trading Inc. (“dYdX”) and is based on the Cosmos SDK and CometBFT proof-of-stake consensus protocol. dYdX Chain is fully decentralized end-to-end, including its consensus mechanism, order-book, matching engine and front end."
  website: https://dydx.exchange/
  docs: https://docs.dydx.exchange/

codebase:
  git-url: https://github.com/dydxprotocol/v4-chain
  settings:
    cosmos-properties:
      registry-url: https://github.com/cosmos/chain-registry/blob/master/dydx/chain.json
      genesis-url: https://raw.githubusercontent.com/dydxopsdao/networks/main/dydx-mainnet-1/genesis.json
    upgrades:
      - name: "genesis"
        height: 1
        recommended-version: "protocol/v2.0.1"
        commit: "31c2a937fc87bb9b7617443e4e5db2b1a2e9bda9"
        go-version: "go1.21"
        ksync-engine: "cometbft-v0.37"
      - name: "v3.0.0"
        height: 7147832
        recommended-version: "protocol/v3.0.2"
        commit: "40a28e49c4300e6a17a5b0a84b134e4a4397758f"
        go-version: "go1.21"
        ksync-engine: "cometbft-v0.37"
      - name: "v4.0.0"
        height: 12791712
        recommended-version: "protocol/v4.0.5"
        commit: "2cd68a9b5491a466be9b40201fc6132cea5a9aaa"
        go-version: "go1.21"
        ksync-engine: "cometbft-v0.38"
      - name: "v4.1.0"
        height: 14404200
        recommended-version: "protocol/v4.1.4"
        commit: "f15e98f09e35adf1f48084de3ac18aae8a3a9337"
        go-version: "go1.21"
        ksync-engine: "cometbft-v0.38"
      - name: "v5.0.0"
        height: 17560000
        recommended-version: "protocol/v5.0.5"
        commit: "a3ea114579299fd1386a980062bdc6d11f9faffe"
        go-version: "go1.22"
        ksync-engine: "cometbft-v0.38"
      - name: "v5.1.0"
        height: 21142000
        recommended-version: "protocol/v5.1.1"
        commit: "c522048088ff4190064374e79a03cada4a4e02e7"
        go-version: "go1.22"
        ksync-engine: "cometbft-v0.38"
      - name: "v5.2.0"
        height: 22170000
        recommended-version: "protocol/v5.2.2"
        commit: "488e4101fbb64489734696c8759cf1051a7934e1"
        go-version: "go1.22"
        ksync-engine: "cometbft-v0.38"
      - name: "v6.0.0"
        height: 26785000
        recommended-version: "protocol/v6.0.4"
        commit: "bb43ac2fc18b897dbedf66234beccf1aa6eb428c"
        go-version: "go1.22"
        ksync-engine: "cometbft-v0.38"
      - name: "v7.0"
        height: 29950000
        recommended-version: "protocol/v7.0.1"
        commit: "b3b12f3f00cf2e350e862d095740c60ebf7b107b"
        go-version: "go1.22"
        ksync-engine: "cometbft-v0.38"

networks:
  # Mainnet pools
  kyve-1:
    pools:
      - id: 13
        runtime: "kyvejs/tendermint"
    integrations:
      ksync:
        binary-name: "dydxprotocold"
        block-sync-pool: 13
        docs-url: "https://docs.dydx.exchange/"
  # Testnet pools
  kaon-1:
    pools:
      - id: 8
        runtime: "kyvejs/tendermint"
      - id: 9
        runtime: "kyvejs/tendermint-ssync"
    integrations:
      ksync:
        binary-name: "dydxprotocold"
        block-sync-pool: 8
        docs-url: "https://docs.dydx.exchange/"
        state-sync-pool: 9
