# Global information
source-id: "noble-1"
config-version: 1
properties:
  title: "Noble"
  hex: "#0e1225"
  logo: "ar://DZP1WPGja9LAa7Vf1P2N-dfDVUlG9lmCkD_psZj47tU"
  description: "Noble is a Cosmos application-specific blockchain purpose-built for native asset issuance. Noble brings the efficiency and interoperability of native assets to the wider Cosmos ecosystem, starting with USDC. Noble’s vision is to be the world’s premier issuance hub for digital assets that connect to other blockchains seamlessly. Noble leverages the Cosmos-SDK – a flexible toolkit that allows developers to incorporate existing modules and to seamlessly integrate custom modules that add virtually unlimited functionality for asset issuers on the Noble blockchain."
  website: https://nobleassets.xyz/
  docs: https://docs.nobleassets.xyz/

codebase:
  git-url: https://github.com/noble-assets/noble
  settings:
    cosmos-properties:
      registry-url: https://github.com/cosmos/chain-registry/blob/master/noble/chain.json
      genesis-name: "v1.0.0"
      genesis-url: https://raw.githubusercontent.com/strangelove-ventures/noble-networks/main/mainnet/noble-1/genesis.json
    upgrades:
      - name: "v1.0.0"
        height: 1
        recommended-version: "v1.0.0"
        commit: "c252a78d36944be21a1e847c6781e10aa43f1066"
        go-version: "go1.19"
        ksync-engine: "tendermint-v0.34"
      - name: "neon"
        height: 119000
        recommended-version: "v2.0.0"
        commit: "2b98e0bb282a723aae64941cc54f52b1f4324330"
        go-version: "go1.19"
        ksync-engine: "tendermint-v0.34"
      - name: "radon"
        height: 1296000
        recommended-version: "v3.0.0"
        commit: "1e5ed6be44fde9b4ec25df067e9aaac76e844be6"
        go-version: "go1.19"
        ksync-engine: "tendermint-v0.34"
      - name: "v3.1.0"
        height: 2672000
        recommended-version: "v3.1.0"
        commit: "d145036dff4677e214de89412738bade5fdbe245"
        go-version: "go1.19"
        ksync-engine: "tendermint-v0.34"
      - name: "argon"
        height: 3408600
        recommended-version: "v4.0.2"
        commit: "2da993039fa78a6818928b8924ee956a72983861"
        go-version: "go1.21"
        ksync-engine: "tendermint-v0.34"
      - name: "v4.0.3"
        height: 5262000
        recommended-version: "v4.0.3"
        commit: "11f64b6cc54e8d3551aeef1ddef423872e2f4c7a"
        go-version: "go1.21"
        ksync-engine: "tendermint-v0.34"
      - name: "fusion"
        height: 5797500
        recommended-version: "v4.1.1"
        commit: "4a2fc1db808e34a12af1e45b253fba661e405378"
        go-version: "go1.21"
        ksync-engine: "tendermint-v0.34"
      - name: "v4.1.2"
        height: 6022000
        recommended-version: "v4.1.2"
        commit: "ede45e577c30510ebde678d567956f307b35371b"
        go-version: "go1.21"
        ksync-engine: "tendermint-v0.34"
      - name: "v4.1.3"
        height: 6139500
        recommended-version: "v4.1.3"
        commit: "eea66f417f52eba93a5ebba491dc085b1046e180"
        go-version: "go1.21"
        ksync-engine: "tendermint-v0.34"
      - name: "v4.1.3"
        height: 6139500
        recommended-version: "v4.1.3"
        commit: "eea66f417f52eba93a5ebba491dc085b1046e180"
        go-version: "go1.21"
        ksync-engine: "tendermint-v0.34"
      - name: "v4.1.3"
        height: 6139500
        recommended-version: "v4.1.3"
        commit: "eea66f417f52eba93a5ebba491dc085b1046e180"
        go-version: "go1.21"
        ksync-engine: "tendermint-v0.34"
      - name: "krypton"
        height: 7947000
        recommended-version: "v5.0.0"
        commit: "3f503860ebab76947d5100eb5560859af2d22838"
        go-version: "go1.21"
        ksync-engine: "tendermint-v0.34"
      - name: "xenon"
        height: 11110000
        recommended-version: "v6.0.0"
        commit: "4ffb44b6c047aa31bb92e0c6e4d29c063b222653"
        go-version: "go1.21"
        ksync-engine: "tendermint-v0.34"
      - name: "numus"
        height: 12240000
        recommended-version: "v7.0.0"
        commit: "56f08ad2d6c8baec66617202f0463f66c9b0fdfe"
        go-version: "go1.21"
        ksync-engine: "tendermint-v0.34"
      - name: "helium"
        height: 15375000
        recommended-version: "v8.0.0"
        commit: "d1cb63ec9c13d60567dce08d78180b4756f0e90f"
        go-version: "go1.22"
        ksync-engine: "cometbft-v0.38"

networks:
  # Mainnet pools
  kyve-1:
    pools:
      - id: 7
        runtime: "kyvejs/tendermint"
      - id: 8
        runtime: "kyvejs/tendermint-ssync"
    integrations:
      ksync:
        binary-name: "nobled"
        block-sync-pool: 7
        docs-url: "https://docs.nobleassets.xyz"
        state-sync-pool: 8
  # Testnet pools
  kaon-1:
    pools:
      - id: 12
        runtime: "kyvejs/tendermint"
      - id: 13
        runtime: "kyvejs/tendermint-ssync"
    integrations:
      ksync:
        binary-name: "nobled"
        block-sync-pool: 12
        docs-url: "https://docs.nobleassets.xyz/"
        state-sync-pool: 13
