# Global information
source-id: "noble-1"
config-version: 1
properties:
  title: "Noble"
  hex: "#0e1225"
  logo: "ar://DZP1WPGja9LAa7Vf1P2N-dfDVUlG9lmCkD_psZj47tU"
  description: "Noble is a Cosmos application-specific blockchain purpose-built for native asset issuance. Noble brings the efficiency and interoperability of native assets to the wider Cosmos ecosystem, starting with USDC. Noble’s vision is to be the world’s premier issuance hub for digital assets that connect to other blockchains seamlessly. Noble leverages the Cosmos-SDK – a flexible toolkit that allows developers to incorporate existing modules and to seamlessly integrate custom modules that add virtually unlimited functionality for asset issuers on the Noble blockchain."
  website: https://nobleassets.xyz/
  docs: https://docs.nobleassets.xyz/

codebase:
  git-repo: https://github.com/noble-assets/noble
  settings:
    # Cosmos specific settings for block and snapshot pools
    cosmos-registry: https://github.com/cosmos/chain-registry/blob/master/noble/chain.json
    cosmos-genesis:
      name: "v1.0.0"
      genesis-url: https://raw.githubusercontent.com/strangelove-ventures/noble-networks/main/mainnet/noble-1/genesis.json
    cosmos-upgrades:
      - name: "v1.0.0"
        height: 1
        recommended-version: "v1.0.0"
        ksync-engine: "tendermint"
      - name: "neon"
        height: 119000
        recommended-version: "v2.0.1"
        ksync-engine: "tendermint"
      - name: "radon"
        height: 1296000
        recommended-version: "v3.0.0"
        ksync-engine: "tendermint"
      - name: "v3.1.0"
        height: 2672000
        recommended-version: "v3.1.0"
        ksync-engine: "tendermint"
      - name: "argon"
        height: 3408600
        recommended-version: "v4.0.2"
        ksync-engine: "tendermint"

networks:
  # Mainnet pools
  kyve-1:
    pools:
      - id: 7
        runtime: "kyvejs/tendermint"
      - id: 8
        runtime: "kyvejs/tendermint-ssync"
    integrations:
      ksync:
        binary-name: "nobled"
        block-sync-pool: 7
        docs-url: "https://docs.nobleassets.xyz"
        state-sync-pool: 8
  # Testnet pools
  kaon-1:
    pools:
      - id: 12
        runtime: "kyvejs/tendermint"
      - id: 13
        runtime: "kyvejs/tendermint-ssync"
    integrations:
      ksync:
        binary-name: "nobled"
        block-sync-pool: 12
        docs-url: "https://docs.nobleassets.xyz/"
        state-sync-pool: 13
