archway-1:
  config-version: 1
  networks:
    kaon-1:
      integrations:
        ksync:
          binary-name: archwayd
          block-sync-pool: 2
          docs-url: https://docs.archway.io/
          state-sync-pool: 4
      pools:
      - id: 2
        runtime: kyvejs/tendermint
      - id: 4
        runtime: kyvejs/tendermint-ssync
      properties:
        description: Archway is a Cosmos-native incentivized smart contract chain
          that enables developers to deploy high-performance dapps that earn rewards
          based on the traffic they bring to the network. As developers build and
          launch impactful dapps, they receive a proportional share of network fees,
          inflation, and premiums. At its core, Archway is designed to enable developers
          to capture the value they create through sustainable economic models built
          into the blockchain.
        hex: '#e45121'
        logo: ar://hKb8dVx4E1NCUJ_BlhNOcyfQEta5r38SBXqsfPnAsWE
        title: Archway
    kyve-1:
      integrations:
        ksync:
          binary-name: archwayd
          block-sync-pool: 2
          docs-url: https://docs.archway.io/
          state-sync-pool: 4
      pools:
      - id: 2
        runtime: kyvejs/tendermint
      - id: 4
        runtime: kyvejs/tendermint-ssync
      properties:
        description: Archway is a Cosmos-native incentivized smart contract chain
          that enables developers to deploy high-performance dapps that earn rewards
          based on the traffic they bring to the network. As developers build and
          launch impactful dapps, they receive a proportional share of network fees,
          inflation, and premiums. At its core, Archway is designed to enable developers
          to capture the value they create through sustainable economic models built
          into the blockchain.
        hex: '#e45121'
        logo: ar://hKb8dVx4E1NCUJ_BlhNOcyfQEta5r38SBXqsfPnAsWE
        title: Archway
  source-id: archway-1
axelar-dojo-1:
  config-version: 1
  networks:
    kaon-1:
      integrations:
        ksync:
          binary-name: axelard
          block-sync-pool: 3
          docs-url: https://docs.axelar.dev/
      pools:
      - id: 3
        runtime: kyvejs/tendermint
      properties:
        description: "Axelar is the programmable Web3 interoperability platform, connecting\
          \ over 50 blockchains via a secure, scalable network \u2013 internet infrastructure\
          \ for the world\u2019s next super app. For partners ranging from Uniswap\
          \ to Circle, Axelar enables scalable cross-chain solutions. Users interact\
          \ with any asset in one click. Developers span multiple blockchains as though\
          \ building on one, supported by a simple API and a permissionless ecosystem\
          \ of tools and service providers. Backers include Binance, Coinbase, Dragonfly,\
          \ Galaxy and Polychain. See what full-stack interoperability can do for\
          \ your dApp. Learn more at https://axelar.network."
        hex: '#5cc1fa'
        logo: ar://iW1jN99yH_gdQtRhf5J_lVwOIu8p_i7FyxEgoQAkWxU
        title: Axelar
    kyve-1:
      integrations:
        ksync:
          binary-name: axelard
          block-sync-pool: 3
          docs-url: https://docs.axelar.dev/
      pools:
      - id: 3
        runtime: kyvejs/tendermint
      properties:
        description: "Axelar is the programmable Web3 interoperability platform, connecting\
          \ over 50 blockchains via a secure, scalable network \u2013 internet infrastructure\
          \ for the world\u2019s next super app. For partners ranging from Uniswap\
          \ to Circle, Axelar enables scalable cross-chain solutions. Users interact\
          \ with any asset in one click. Developers span multiple blockchains as though\
          \ building on one, supported by a simple API and a permissionless ecosystem\
          \ of tools and service providers. Backers include Binance, Coinbase, Dragonfly,\
          \ Galaxy and Polychain. See what full-stack interoperability can do for\
          \ your dApp. Learn more at https://axelar.network."
        hex: '#5cc1fa'
        logo: ar://iW1jN99yH_gdQtRhf5J_lVwOIu8p_i7FyxEgoQAkWxU
        title: Axelar
  source-id: axelar-dojo-1
celestia:
  config-version: 1
  networks:
    kaon-1:
      integrations:
        ksync:
          binary-name: celestia-appd
          block-sync-pool: 14
          docs-url: https://docs.celestia.org/
          state-sync-pool: 15
      pools:
      - id: 14
        runtime: kyvejs/tendermint
      - id: 15
        runtime: kyvejs/tendermint-ssync
      properties:
        hex: '#af6fd8'
        logo: ar://TJ83Nah_FaECM0zcKajX-7-JW79iSgi2msbUFYwVMWU
        title: Celestia
  source-id: celestia
cosmoshub-4:
  config-version: 1
  networks:
    kaon-1:
      integrations:
        ksync:
          binary-name: gaiad
          block-sync-pool: 0
          docs-url: https://docs.cosmos.network/
      pools:
      - id: 0
        runtime: kyvejs/tendermint-bsync
      properties:
        description: Serving as the economic center of the Interchain, the Cosmos
          Hub is a blockchain that provides vital ecosystem services. The primary
          token of the Cosmos Hub is the ATOM, but the Hub will support many tokens
          in the future.
        hex: '#1c2049'
        logo: ar://GSK9zAQx1jOnQIhbM20qCoOFYT3EJXIJfwfvT_QhLVM
        title: Cosmos Hub
    kyve-1:
      integrations:
        ksync:
          binary-name: gaiad
          block-sync-pool: 0
          docs-url: https://docs.cosmos.network/
      pools:
      - id: 0
        runtime: kyvejs/tendermint-bsync
      properties:
        description: Serving as the economic center of the Interchain, the Cosmos
          Hub is a blockchain that provides vital ecosystem services. The primary
          token of the Cosmos Hub is the ATOM, but the Hub will support many tokens
          in the future.
        hex: '#1c2049'
        logo: ar://GSK9zAQx1jOnQIhbM20qCoOFYT3EJXIJfwfvT_QhLVM
        title: Cosmos Hub
  source-id: cosmoshub-4
cronosmainnet_25-1:
  config-version: 1
  networks:
    kaon-1:
      integrations:
        ksync:
          binary-name: cronosd
          block-sync-pool: 6
          docs: https://docs.cronos.org/
          state-sync-pool: 7
      pools:
      - id: 6
        runtime: kyvejs/tendermint
      - id: 7
        runtime: kyvejs/tendermint-ssync
      properties:
        description: 'Cronos (cronos.org) is the leading Ethereum-compatible layer
          1 blockchain network built on the Cosmos SDK, supported by Crypto.com, Crypto.org,
          and more than 500 app developers and partners. Today, the #CROfam ecosystem
          represents an addressable user base of more than 80 million people worldwide.
          Our mission is to make it easy and safe for the next billion crypto users
          to adopt Web3, with a focus on decentralized applications in the DeFi, NFTs
          and GameFi verticals.'
        hex: '#191b34'
        logo: ar://BbNmwRFv11y68Jiele3wxZNYQTqRVn_ZK6BwJ5S2MCE
        title: Cronos
    kyve-1:
      integrations:
        ksync:
          binary-name: cronosd
          block-sync-pool: 5
          docs: https://docs.cronos.org/
          state-sync-pool: 6
      pools:
      - id: 5
        runtime: kyvejs/tendermint
      - id: 6
        runtime: kyvejs/tendermint-ssync
      properties:
        description: 'Cronos (cronos.org) is the leading Ethereum-compatible layer
          1 blockchain network built on the Cosmos SDK, supported by Crypto.com, Crypto.org,
          and more than 500 app developers and partners. Today, the #CROfam ecosystem
          represents an addressable user base of more than 80 million people worldwide.
          Our mission is to make it easy and safe for the next billion crypto users
          to adopt Web3, with a focus on decentralized applications in the DeFi, NFTs
          and GameFi verticals.'
        hex: '#191b34'
        logo: ar://BbNmwRFv11y68Jiele3wxZNYQTqRVn_ZK6BwJ5S2MCE
        title: Cronos
  source-id: cronosmainnet_25-1
dydx-mainnet-1:
  config-version: 1
  networks:
    kaon-1:
      integrations:
        ksync:
          binary-name: dydxprotocold
          block-sync-pool: 8
          docs-url: https://docs.dydx.exchange/
          state-sync-pool: 9
      pools:
      - id: 8
        runtime: kyvejs/tendermint
      - id: 9
        runtime: kyvejs/tendermint-ssync
      properties:
        hex: '#12121d'
        logo: ar://34RVRPI9Ume67ZdNhqwQ42GkZa0NoulBXNiJFJQZ6uc
        title: dYdX
  source-id: dydx-mainnet-1
noble-1:
  config-version: 1
  networks:
    kaon-1:
      integrations:
        ksync:
          binary-name: nobled
          block-sync-pool: 12
          docs-url: https://docs.nobleassets.xyz/
          state-sync-pool: 13
      pools:
      - id: 12
        runtime: kyvejs/tendermint
      - id: 13
        runtime: kyvejs/tendermint-ssync
      properties:
        description: "Noble is a Cosmos application-specific blockchain purpose-built\
          \ for native asset issuance. Noble brings the efficiency and interoperability\
          \ of native assets to the wider Cosmos ecosystem, starting with USDC. Noble\u2019\
          s vision is to be the world\u2019s premier issuance hub for digital assets\
          \ that connect to other blockchains seamlessly. Noble leverages the Cosmos-SDK\
          \ \u2013 a flexible toolkit that allows developers to incorporate existing\
          \ modules and to seamlessly integrate custom modules that add virtually\
          \ unlimited functionality for asset issuers on the Noble blockchain."
        hex: '#0e1225'
        logo: ar://DZP1WPGja9LAa7Vf1P2N-dfDVUlG9lmCkD_psZj47tU
        title: Noble
    kyve-1:
      integrations:
        ksync:
          binary-name: nobled
          block-sync-pool: 7
          docs-url: https://docs.nobleassets.xyz
          state-sync-pool: 8
      pools:
      - id: 7
        runtime: kyvejs/tendermint
      - id: 8
        runtime: kyvejs/tendermint-ssync
      properties:
        description: "Noble is a Cosmos application-specific blockchain purpose-built\
          \ for native asset issuance. Noble brings the efficiency and interoperability\
          \ of native assets to the wider Cosmos ecosystem, starting with USDC. Noble\u2019\
          s vision is to be the world\u2019s premier issuance hub for digital assets\
          \ that connect to other blockchains seamlessly. Noble leverages the Cosmos-SDK\
          \ \u2013 a flexible toolkit that allows developers to incorporate existing\
          \ modules and to seamlessly integrate custom modules that add virtually\
          \ unlimited functionality for asset issuers on the Noble blockchain."
        hex: '#0e1225'
        logo: ar://DZP1WPGja9LAa7Vf1P2N-dfDVUlG9lmCkD_psZj47tU
        title: Noble
  source-id: noble-1
osmosis-1:
  config-version: 1
  networks:
    kaon-1:
      integrations:
        ksync:
          binary-name: osmosisd
          block-sync-pool: 1
          docs-url: https://docs.osmosis.zone/
          state-sync-pool: 5
      pools:
      - id: 1
        runtime: kyvejs/tendermint
      - id: 5
        runtime: kyvejs/tendermint-ssync
      properties:
        description: Osmosis, dubbed the Interchain Liquidity Lab, is a decentralized
          exchange (DEX) for Cosmos, an ecosystem of sovereign, interoperable blockchains
          all connected trustlessly over IBC, the Inter-Blockchain Communication Protocol.
        hex: '#8d07c7'
        logo: ar://u8kGlBx37seQCO1X5vQsc3Q8iO2CE-BHqsm0937poak
        title: Osmosis
    kyve-1:
      integrations:
        ksync:
          binary-name: osmosisd
          block-sync-pool: 1
          docs-url: https://docs.osmosis.zone/
      pools:
      - id: 1
        runtime: kyvejs/tendermint
      properties:
        description: Osmosis, dubbed the Interchain Liquidity Lab, is a decentralized
          exchange (DEX) for Cosmos, an ecosystem of sovereign, interoperable blockchains
          all connected trustlessly over IBC, the Inter-Blockchain Communication Protocol.
        hex: '#8d07c7'
        logo: ar://u8kGlBx37seQCO1X5vQsc3Q8iO2CE-BHqsm0937poak
        title: Osmosis
  source-id: osmosis-1
zeta_7000-1:
  config-version: 1
  networks:
    kaon-1:
      integrations:
        ksync:
          binary-name: zetacored
          block-sync-pool: 10
          docs-url: https://www.zetachain.com/docs/
          state-sync-pool: 11
      pools:
      - id: 10
        runtime: kyvejs/tendermint
      - id: 11
        runtime: kyvejs/tendermint-ssync
      properties:
        hex: '#235643'
        logo: ar://FsZbG0a3aVwfRrxgFRYklEknIsGHnGTX6YiQJwhtnH8
        title: ZetaChain
  source-id: zeta_7000-1
