archway-1:
  chain:
    chain_id: archway-1
    hex: '#e45121'
    title: Archway
  kaon-1:
    block_source_id: 2
    state_source_id: 4
  kyve-1:
    block_source_id: 2
axelar-dojo-1:
  chain:
    chain_id: axelar-dojo-1
    hex: '#5cc1fa'
    title: Axelar
  kaon-1:
    block_source_id: 3
  kyve-1:
    block_source_id: 3
cosmoshub-4:
  chain:
    chain_id: cosmoshub-4
    hex: '#6f3048'
    title: Cosmos Hub
  kaon-1:
    block_source_id: 0
  kyve-1:
    block_source_id: 0
cronosmainnet_25-1:
  chain:
    chain_id: cronosmainnet_25-1
    hex: '#191b34'
    title: Cronos
  kaon-1:
    block_source_id: 6
    state_source_id: 7
  kyve-1: {}
osmosis-1:
  chain:
    chain_id: osmosis-1
    hex: '#8d07c7'
    title: Osmosis
  kaon-1:
    block_source_id: 1
    state_source_id: 5
  kyve-1:
    block_source_id: 1
