# Global information
source-id: "xion-mainnet-1"
config-version: 1
properties:
  title: "XION"
  hex: "#000000"
  logo: "ar://YTPWZRQ5-ORhqSXH03uCXMSQe4vqNxeuIQrirAmke9U"
  description: "XION empowers developers to build, launch and scale consumer-ready products from the ground up, removing technical barriers for all users through its Chain Abstraction."
  website: https://xion.burnt.com/
  docs: https://docs.burnt.com/xion

codebase:
  git-url: https://github.com/burnt-labs/xion
  settings:
    cosmos-properties:
      registry-url: https://github.com/cosmos/chain-registry/blob/master/xion/chain.json
      genesis-url: https://raw.githubusercontent.com/burnt-labs/burnt-networks/refs/heads/main/mainnet/xion-mainnet-1/genesis.json
    upgrades:
      - name: "genesis"
        height: 1
        recommended-version: "v4.0.0"
        commit: "f13a74c7cf5a562d6902263e53c5ee4f0a9dfefe"
        go-version: "go1.21"
        ksync-engine: "cometbft-v0.37"
      - name: "v6"
        height: 606689
        recommended-version: "v6.0.0"
        commit: "96670570350b6dc885dbdeb0bd03e37830b512b1"
        go-version: "go1.21"
        ksync-engine: "cometbft-v0.37"
      - name: "v7.0.0"
        height: 1637000
        recommended-version: "v7.0.0"
        commit: "01c5275070ef8d73aa92180deaa70d4d201d6c45"
        go-version: "go1.21"
        ksync-engine: "cometbft-v0.37"
      - name: "v9"
        height: 1960000
        recommended-version: "v9.0.1"
        commit: "0dd06f1d814603ae7193417fedda192fc05c9280"
        go-version: "go1.22"
        ksync-engine: "cometbft-v0.37"
      - name: "v11"
        height: 3150000
        recommended-version: "v11.0.1"
        commit: "0fa1ea9d9130b0955ef2fd9c25a0eab0099327aa"
        go-version: "go1.22"
        ksync-engine: "cometbft-v0.38"
      - name: "v14"
        height: 3586500
        recommended-version: "v14.1.0"
        commit: "7f0de62df6d2e941b8cc04a413124623ef20f49c"
        go-version: "go1.22"
        ksync-engine: "cometbft-v0.38"
      - name: "v16"
        height: 5825000
        recommended-version: "v16.0.0"
        commit: "133282bfba15139e8b9c39de547b6a937a483c37"
        go-version: "go1.23"
        ksync-engine: "cometbft-v0.38"
      - name: "v17"
        height: 5942000
        recommended-version: "v17.0.0"
        commit: "42ea2dcadc0e73271cf33dd462de460bc7c239b2"
        go-version: "go1.23"
        ksync-engine: "cometbft-v0.38"

networks:
  # Mainnet pools
  kyve-1:
    pools:
      - id: 16
        runtime: "kyvejs/tendermint"
      - id: 17
        runtime: "kyvejs/tendermint-ssync"
    integrations:
      ksync:
        binary-name: "xiond"
        block-sync-pool: 16
        docs-url: "https://docs.burnt.com/xion"
        state-sync-pool: 17

  # Testnet pools
  kaon-1:
    pools:
      - id: 36
        runtime: "kyvejs/tendermint"
      - id: 37
        runtime: "kyvejs/tendermint-ssync"
    integrations:
      ksync:
        binary-name: "xiond"
        block-sync-pool: 36
        docs-url: "https://docs.burnt.com/xion"
        state-sync-pool: 37
