# Global information
source-id: "zetachain_7000-1"
config-version: 1
properties:
  title: "ZetaChain"
  hex: "#235643"
  logo: "ar://FsZbG0a3aVwfRrxgFRYklEknIsGHnGTX6YiQJwhtnH8"
  description: "ZetaChain is the foundational, public blockchain that enables omnichain, generic smart contracts and messaging between any blockchain. It solves the problems of “cross-chain” and “multi-chain” and aims to open the crypto and global financial ecosystem to anyone. ZetaChain envisions and supports a truly fluid, multi-chain crypto ecosystem, where users and developers can move between and appreciate the benefits of any blockchain: payments, DeFi, liquidity, games, art, social graphs, performance, security, privacy, and so on."
  website: https://www.zetachain.com/
  docs: https://www.zetachain.com/docs/

codebase:
  git-url: https://github.com/zeta-chain/node
  settings:
    cosmos-properties:
      registry-url: https://github.com/cosmos/chain-registry/blob/master/zetachain/chain.json
      genesis-name: "v10.1.0"
      genesis-url: https://zetachain.blockpi.network/rpc/v1/public/genesis
    upgrades:
      - name: "v10.1.0"
        height: 1
        recommended-version: "v10.1.5"
        commit: "b1c5881e4488ddfb5e73ccd3b0d417c3c11a3ae7"
        go-version: "go1.20"
        ksync-engine: "tendermint-v0.34"
      - name: "v11.0.0"
        height: 1257000
        recommended-version: "v11.0.5"
        commit: "825d9f87bb13e28ec916b8abaafe8b5534eace60"
        go-version: "go1.20"
        ksync-engine: "tendermint-v0.34"
      - name: "v12.0.0"
        height: 1424500
        recommended-version: "v12.0.2"
        commit: "67cad54a5c1a1b46b599e74f56c664e3cee214aa"
        go-version: "go1.20"
        ksync-engine: "tendermint-v0.34"
      - name: "v12.1.0"
        height: 1529050
        recommended-version: "v12.1.1"
        commit: "440b61dae573c6bde8347e564cea3afd9b8f8d2d"
        go-version: "go1.20"
        ksync-engine: "tendermint-v0.34"
      - name: "v12.2.0"
        height: 1549750
        recommended-version: "v12.2.5"
        commit: "54d7613a90312cc97c6020e4cdba6a63ae1e5734"
        go-version: "go1.20"
        ksync-engine: "tendermint-v0.34"
      - name: "v14"
        height: 2074730
        recommended-version: "v14.0.1"
        commit: "4654c9065f5b0a8e01878377f17d2027be95f25d"
        go-version: "go1.20"
        ksync-engine: "tendermint-v0.34"
      - name: "v17"
        height: 3388200
        recommended-version: "v17.0.1"
        commit: "8a34fbe7d602865451fb41eb0eaa9564bba8a849"
        go-version: "go1.20"
        ksync-engine: "tendermint-v0.34"
      - name: "v18"
        height: 3388200
        recommended-version: "v18.0.1"
        commit: "855e0ed3811bdf47f96b5f3a42ba2d80e4030349"
        go-version: "go1.20"
        ksync-engine: "tendermint-v0.34"

networks:
  # Testnet pools
  kaon-1:
    pools:
      - id: 10
        runtime: "kyvejs/tendermint"
      - id: 11
        runtime: "kyvejs/tendermint-ssync"
    integrations:
      ksync:
        binary-name: "zetacored"
        block-sync-pool: 10
        docs-url: "https://www.zetachain.com/docs/"
        state-sync-pool: 11
