# Global information
source-id: "zeta_7000-1"
config-version: 1
properties:
  title: "ZetaChain"
  hex: "#235643"
  logo: "ar://FsZbG0a3aVwfRrxgFRYklEknIsGHnGTX6YiQJwhtnH8"
  description: "ZetaChain is the foundational, public blockchain that enables omnichain, generic smart contracts and messaging between any blockchain. It solves the problems of “cross-chain” and “multi-chain” and aims to open the crypto and global financial ecosystem to anyone. ZetaChain envisions and supports a truly fluid, multi-chain crypto ecosystem, where users and developers can move between and appreciate the benefits of any blockchain: payments, DeFi, liquidity, games, art, social graphs, performance, security, privacy, and so on."

networks:
  # Testnet pools
  kaon-1:
    pools:
      - id: 10
        runtime: "kyvejs/tendermint"
      - id: 11
        runtime: "kyvejs/tendermint-ssync"
    integrations:
      ksync:
        binary-name: "zetacored"
        block-sync-pool: 10
        docs-url: "https://www.zetachain.com/docs/"
        state-sync-pool: 11
