# Global information
source-id: "cosmoshub-4"
config-version: 1
properties:
  title: "Cosmos Hub"
  hex: "#1c2049"
  logo: "ar://GSK9zAQx1jOnQIhbM20qCoOFYT3EJXIJfwfvT_QhLVM"
  description: "Serving as the economic center of the Interchain, the Cosmos Hub is a blockchain that provides vital ecosystem services. The primary token of the Cosmos Hub is the ATOM, but the Hub will support many tokens in the future."

networks:
  # Mainnet pools
  kyve-1:
    pools:
      - id: 0
        runtime: "kyvejs/tendermint-bsync"
    integrations:
      ksync:
        binary-name: "gaiad"
        block-sync-pool: 0
        docs-url: "https://docs.cosmos.network/"

  # Testnet pools
  kaon-1:
    pools:
      - id: 0
        runtime: "kyvejs/tendermint-bsync"
      - id: 18
        runtime: "kyvejs/tendermint"
      - id: 19
        runtime: "kyvejs/tendermint-ssync"
    integrations:
      ksync:
        binary-name: "gaiad"
        block-sync-pool: 18
        docs-url: "https://docs.cosmos.network/"
        state-sync-pool: 19
