# Global information
source-id: "cosmoshub-4"
config-version: 1
properties:
  title: "Cosmos Hub"
  hex: "#1c2049"
  logo: "ar://GSK9zAQx1jOnQIhbM20qCoOFYT3EJXIJfwfvT_QhLVM"
  description: "Serving as the economic center of the Interchain, the Cosmos Hub is a blockchain that provides vital ecosystem services. The primary token of the Cosmos Hub is the ATOM, but the Hub will support many tokens in the future."

codebase:
  git-url: https://github.com/cosmos/gaia
  settings:
    cosmos-properties:
      registry-url: https://github.com/cosmos/chain-registry/blob/master/cosmoshub/chain.json
      genesis-name: "v4"
      genesis-url: https://github.com/cosmos/mainnet/raw/master/genesis/genesis.cosmoshub-4.json.gz
    upgrades:
      - name: "v4"
        height: 5200791
        recommended-version: "v4.2.1"
        commit: "dbd8a6fb522c571debf958837f9113c56d418f6b"
        go-version: "go1.15"
        ksync-engine: "tendermint-v0.34"
        cosmos-sdk-version: "v0.42.4"
      - name: "Gravity-DEX"
        height: 6910000
        recommended-version: "v5.0.8"
        commit: "b72cc994f7156c8a8991e6beed2dde84ad274588"
        go-version: "go1.16"
        ksync-engine: "tendermint-v0.34"
        cosmos-sdk-version: "v0.42.10"
      - name: "Vega"
        height: 8695000
        recommended-version: "v6.0.4"
        commit: "305668ab9d962431c79d718bb0ffdeec77a46439"
        go-version: "go1.17"
        ksync-engine: "tendermint-v0.34"
        cosmos-sdk-version: "v0.44.6"
      - name: "v7-Theta"
        height: 10085397
        recommended-version: "v7.1.1"
        commit: "b2504c1e28eae936477c7b06ae4c0f058613a4e8"
        go-version: "go1.18"
        ksync-engine: "tendermint-v0.34"
        cosmos-sdk-version: "v0.45.9"
      - name: "v8-Rho"
        height: 14099412
        recommended-version: "v8.0.1"
        commit: "890ab3aa2e5788537b0d2ebc9bafdc968340e0e5"
        go-version: "go1.18"
        ksync-engine: "tendermint-v0.34"
        cosmos-sdk-version: "v0.45.14"
      - name: "v9-Lambda"
        height: 14470501
        recommended-version: "v9.0.3"
        commit: "05b6b87d3c9121e933eab437772ea56f33ae268f"
        go-version: "go1.18"
        ksync-engine: "tendermint-v0.34"
        cosmos-sdk-version: "v0.45.15-ics"
      - name: "v9.1.0"
        height: 15213800
        recommended-version: "v9.1.1"
        commit: "66494d1ec72cfa0f8800aa8f1545e19d2af47e47"
        go-version: "go1.18"
        ksync-engine: "tendermint-v0.34"
        cosmos-sdk-version: "v0.45.15-ics"
      - name: "v10"
        height: 15816200
        recommended-version: "v10.0.2"
        commit: "a2b14cdd568273e12b80579b4e22681df95b4cb9"
        go-version: "go1.20"
        ksync-engine: "tendermint-v0.34"
        cosmos-sdk-version: "v0.45.16-ics"
      - name: "v11"
        height: 16596000
        recommended-version: "v11.0.0"
        commit: "541a8d86af28231c767d6db52eb88ba9496ad0c4"
        go-version: "go1.20"
        ksync-engine: "tendermint-v0.34"
        cosmos-sdk-version: "v0.45.16-ics"
      - name: "v12"
        height: 16985500
        recommended-version: "v12.0.0"
        commit: "6f8067d76ce30996f83645862153ccfaf5f13dd1"
        go-version: "go1.20"
        ksync-engine: "tendermint-v0.34"
        cosmos-sdk-version: "v0.45.16-ics"
      - name: "v13"
        height: 17380000
        recommended-version: "v13.0.2"
        commit: "2406abb61856b61904ff06c7be2a355babcc3dfc"
        go-version: "go1.20"
        ksync-engine: "tendermint-v0.34"
        cosmos-sdk-version: "v0.45.16"
      - name: "v14"
        height: 18262000
        recommended-version: "v14.1.0"
        commit: "0d9408e9169488707f1ad423e87d0df84a30431f"
        go-version: "go1.20"
        ksync-engine: "tendermint-v0.34"
        cosmos-sdk-version: "v0.45.16"
      - name: "v15"
        height: 19639600
        recommended-version: "v15.1.0"
        commit: "1e7b5171ff1d6c8626aa4a0f049a10fefd69823e"
        go-version: "go1.21"
        ksync-engine: "cometbft-v0.37"
        cosmos-sdk-version: "v0.47.10-ics-lsm"
      - name: "v15"
        height: 19939000
        recommended-version: "v15.2.0"
        commit: "7281c9b9dc4e3087ee87f5b24e416802b52e8661"
        go-version: "go1.21"
        ksync-engine: "cometbft-v0.37"
        cosmos-sdk-version: "v0.47.10-ics-lsm"
      - name: "v16"
        height: 20440500
        recommended-version: "v16.0.0"
        commit: "ebebaac5bf9f19ca68eaa70f6e61287c0e57fb8c"
        go-version: "go1.21"
        ksync-engine: "cometbft-v0.37"
        cosmos-sdk-version: "v0.47.13-ics-lsm"
      - name: "v17"
        height: 20739800
        recommended-version: "v17.3.0"
        commit: "24f6d24f029328ee40b3d821cfd12dbcf40bbbe5"
        go-version: "go1.21"
        ksync-engine: "cometbft-v0.37"
        cosmos-sdk-version: "v0.47.15-ics-lsm"
      - name: "v18"
        height: 21330500
        recommended-version: "v18.1.0"
        commit: "58b4e54a95c7fc6a64272ccd0f09f46213c005ad"
        go-version: "go1.22"
        ksync-engine: "cometbft-v0.37"
        cosmos-sdk-version: "v0.47.16-ics-lsm"
      - name: "v19"
        height: 21835200
        recommended-version: "v19.2.0"
        commit: "1d52b3d434d5d78561c3628ef351b88890ec7f7f"
        go-version: "go1.22"
        ksync-engine: "cometbft-v0.38"
        cosmos-sdk-version: "v0.50.9-lsm"
      - name: "v20"
        height: 22443500
        recommended-version: "v20.0.0"
        commit: "2dba9d471ef73b0a99e844bf55a44ddae700ea06"
        go-version: "go1.22"
        ksync-engine: "cometbft-v0.38"
        cosmos-sdk-version: "v0.50.9-lsm"

networks:
  # Mainnet pools
  kyve-1:
    pools:
      - id: 0
        runtime: "kyvejs/tendermint-bsync"
    integrations:
      ksync:
        binary-name: "gaiad"
        block-sync-pool: 0
        docs-url: "https://docs.cosmos.network/"

  # Testnet pools
  kaon-1:
    pools:
      - id: 0
        runtime: "kyvejs/tendermint-bsync"
      - id: 18
        runtime: "kyvejs/tendermint"
      - id: 19
        runtime: "kyvejs/tendermint-ssync"
    integrations:
      ksync:
        binary-name: "gaiad"
        block-sync-pool: 18
        docs-url: "https://docs.cosmos.network/"
        state-sync-pool: 19
