# Global information
source-id: "cosmoshub-4"
config-version: 1
properties:
  title: "Cosmos Hub"
  hex: "#1c2049"
  logo: "ar://GSK9zAQx1jOnQIhbM20qCoOFYT3EJXIJfwfvT_QhLVM"

networks:
  # Mainnet pools
  kyve-1:
    pools:
      - id: 0
        runtime: "kyvejs/tendermint-bsync"
    integrations:
      ksync:
        binary-name: "gaiad"
        block-sync-pool: 0
        docs-url: "https://docs.cosmos.network/"

  # Testnet pools
  kaon-1:
    pools:
      - id: 0
        runtime: "kyvejs/tendermint-bsync"
    integrations:
      ksync:
        binary-name: "gaiad"
        block-sync-pool: 0
        docs-url: "https://docs.cosmos.network/"