# Global information
source-id: "celestia"
config-version: 1
properties:
  title: "Celestia"
  hex: "#af6fd8"
  logo: "ar://TJ83Nah_FaECM0zcKajX-7-JW79iSgi2msbUFYwVMWU"
  description: Celestia is a modular data availability network that securely scales with the number of users, making it easy for anyone to launch their own blockchain.
  website: https://celestia.org/
  docs: https://docs.celestia.org/

codebase:
  git-url: https://github.com/celestiaorg/celestia-app
  settings:
    cosmos-properties:
      registry-url: https://github.com/cosmos/chain-registry/blob/master/celestia/chain.json
      genesis-name: "v1.7.0"
      genesis-url: https://raw.githubusercontent.com/celestiaorg/networks/master/celestia/genesis.json
    upgrades:
      - name: "v1.9.0"
        height: 1
        recommended-version: "v1.9.0"
        commit: "ad18465a88000a5b45ceb63efc7d46efaaa56f2c"
        go-version: "go1.22"
        ksync-engine: "celestia-core-v0.34"

networks:
  # Mainnet pools
  kyve-1:
    pools:
      - id: 9
        runtime: "kyvejs/tendermint"
      - id: 10
        runtime: "kyvejs/tendermint-ssync"
    integrations:
      ksync:
        binary-name: "celestia-appd"
        block-sync-pool: 9
        docs: "https://docs.celestia.org/"
        state-sync-pool: 10

  # Testnet pools
  kaon-1:
    pools:
      - id: 14
        runtime: "kyvejs/tendermint"
      - id: 15
        runtime: "kyvejs/tendermint-ssync"
    integrations:
      ksync:
        binary-name: "celestia-appd"
        block-sync-pool: 14
        docs-url: "https://docs.celestia.org/"
        state-sync-pool: 15
