# Global information
source-id: "celestia"
config-version: 1
properties:
  title: "Celestia"
  hex: "#af6fd8"
  logo: "ar://TJ83Nah_FaECM0zcKajX-7-JW79iSgi2msbUFYwVMWU"
  description: Celestia is a modular data availability network that securely scales with the number of users, making it easy for anyone to launch their own blockchain.
  website: https://celestia.org/
  docs: https://docs.celestia.org/

codebase:
  git-repo: https://github.com/celestiaorg/celestia-app
  settings:
    # Cosmos specific settings for block and snapshot pools
    cosmos-registry: https://github.com/cosmos/chain-registry/blob/master/celestia/chain.json
    cosmos-genesis:
      name: "v1.7.0"
      genesis-url: https://raw.githubusercontent.com/celestiaorg/networks/master/celestia/genesis.json
    cosmos-upgrades:
      - name: "v1.7.0"
        height: 1
        recommended-version: "v1.7.0"
        commit: "915847191e80d836f862eea2664949d9a240abea"
        go-version: "go1.22"
        ksync-engine: "tendermint-celestiacore"

networks:
  # Testnet pools
  kaon-1:
    pools:
      - id: 14
        runtime: "kyvejs/tendermint"
      - id: 15
        runtime: "kyvejs/tendermint-ssync"
    integrations:
      ksync:
        binary-name: "celestia-appd"
        block-sync-pool: 14
        docs-url: "https://docs.celestia.org/"
        state-sync-pool: 15
