# Global information
source-id: "source-1"
config-version: 1
properties:
  title: "Source"
  hex: "#d81efd"
  logo: "ar://ch5vZrkVpu8EVQCvgm3nzFkmVLlXVq5mYQvWE5VWpv8"
  description: "$SOURCE is a comprehensive blockchain technology suite for individuals, enterprises and developers to easily use, integrate and build web3.0 applications. It is a broad-spectrum technology ecosystem that transforms centralized web tools and financial instruments into decentralized ones."
  website: https://www.sourceprotocol.io/
  docs: https://docs.sourceprotocol.io/

codebase:
  git-url: https://github.com/Source-Protocol-Cosmos/source
  settings:
    cosmos-properties:
      registry-url: https://github.com/cosmos/chain-registry/blob/master/source/chain.json
      genesis-name: "v3.0.1"
      genesis-url: https://raw.githubusercontent.com/Source-Protocol-Cosmos/mainnet/master/source-1/genesis.json
    upgrades:
      - name: "v3.0.1"
        height: 1
        recommended-version: "v3.0.1"
        commit: "2aae45f6e2d23f6c81c02075b74ee9f5b7598e3e"
        go-version: "go1.19"
        ksync-engine: "tendermint-v0.34"

networks:
  # Mainnet pools
  kyve-1:
    pools:
      - id: 11
        runtime: "kyvejs/tendermint"
      - id: 12
        runtime: "kyvejs/tendermint-ssync"
    integrations:
      ksync:
        binary-name: "sourced"
        block-sync-pool: 11
        docs-url: "https://docs.sourceprotocol.io/"
        state-sync-pool: 12

  # Testnet pools
  kaon-1:
    pools:
      - id: 24
        runtime: "kyvejs/tendermint"
      - id: 25
        runtime: "kyvejs/tendermint-ssync"
    integrations:
      ksync:
        binary-name: "sourced"
        block-sync-pool: 24
        docs-url: "https://docs.sourceprotocol.io/"
        state-sync-pool: 25
