name: Merge Source Configs and Create Release

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  merge_yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Merge Source Configs
        run: python merge_configs.py
        working-directory: ${{ github.workspace }}

      - name: Create Release
        if: (github.event.pull_request.merged == true) || (github.event.ref == 'refs/heads/main')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            registry.yml
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
